[build]
# Leave base empty unless code lives in a subfolder
publish = "dist" # Use "build" if you're using Create React App
command = "npm run build"

[dev]
# Optional: local dev config if using Netlify CLI
port = 8888
autoLaunch = true

[functions]
# If using Netlify serverless functions later
directory = "netlify/functions"